spring.application.name=sb-ecom

# PostgreSQL Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/e-commerce
spring.datasource.username=postgres
spring.datasource.password=Pravin@123
spring.datasource.driver-class-name=org.postgresql.Driver

project.image=images/

# Logging - Set to INFO so the console isn't flooded!
logging.level.org.springframework=INFO
logging.level.org.springframework.security=INFO
logging.level.com.example.securitydemo=INFO
# Keep this as DEBUG so we can see the CREATE TABLE statements
logging.level.org.hibernate.SQL=DEBUG 

# JWT Configuration
spring.app.jwtSecret=mySecretKey123912738aopsgjnspkmndfsopkvajoirjg94gf2opfng2moknm
spring.app.jwtExpirationMs=3000000
spring.app.jwtCookie=SpringBootEcom

# JPA & Hibernate Settings
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# THIS IS THE MAGIC LINE TO CREATE THE TABLES:
spring.jpa.hibernate.ddl-auto=update

# Wait for tables to be created before running any startup SQL/Runners
spring.jpa.defer-datasource-initialization=true